In [1]:
import pandas as pd

In [92]:
df = pd.read_excel('e:\HSTAR009 Analysis V3_Wits RHI. UPDATED.xlsx', sheet_name='MASTER', usecols='AO:BG', nrows=815)

In [97]:

#df1 = df.groupby('Q7').ID.count().reset_index()
#df2 = df.groupby('Q12').ID.count().reset_index()

#df3 = df3.merge(df2, left_on='Q7', right_on='Q12', how='outer',suffixes=('_Q7', '_Q12'))
df3.to_excel('e:\\results.xlsx')

In [98]:
df3

,Q7,ID_Q7,Q3,ID_Q3,Q4,ID_Q7,Q5,ID_Q5,Q6,ID_Q7,Q8,ID_Q8,Q9,ID_Q7,Q10,ID_Q10,Q11,ID_Q7,Q12,ID_Q12
0,0.0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN
2,2.0,1,2.0,1.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0
3,3.0,5,3.0,2.0,3.0,4.0,3.0,4.0,3.0,1.0,3.0,11.0,3.0,1.0,3.0,5.0,3.0,3.0,3.0,4.0
4,4.0,8,4.0,10.0,4.0,12.0,4.0,10.0,4.0,13.0,4.0,13.0,4.0,16.0,4.0,10.0,4.0,14.0,4.0,15.0
5,5.0,24,5.0,33.0,5.0,31.0,5.0,32.0,5.0,31.0,5.0,21.0,5.0,29.0,5.0,31.0,5.0,27.0,5.0,27.0

In [99]:
df.groupby('Answered').ID.count().reset_index()

   Answered   ID
0       0.0  164
1       1.0  362

In [104]:
df.groupby('Q13').ID.count().reset_index().to_excel('e:\\resultsQ13.xlsx')

In [105]:
df.groupby('Q14').ID.count().reset_index().to_excel('e:\\resultsQ14.xlsx')

In [106]:
df.groupby('Q15').ID.count().reset_index().to_excel('e:\\resultsQ15.xlsx')

In [21]:
df.Comments = df.Comments.replace(['1st attempt No Answer 14/3/19,'], 
                                    ['answered'])

In [22]:
df

,Follow up caller,Comments,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,ID
0,Cleo,...,Y,Did not understand why I would use the app,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,Mondii,answered,No,Did not use the APP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,Paul,App was easy to use,Yes,1,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,Yes,NaN,Non,3
3,Cleo,AT CALL AFTER 4,Y,COMPLETED THE SURVEY AT THE END,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,Mondii,Busy cant talk,N busy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,Mondii,completed,y,1,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,4.0,4.0,Y,NaN,NaN,6
6,Mondii,Completed,Y,1,5.0,5.0,5.0,5.0,4.0,3.0,5.0,5.0,4.0,3.0,Y,NaN,NaN,7
7,Mondii,completed,Y,1,4.0,4.0,4.0,4.0,5.0,3.0,4.0,4.0,3.0,4.0,Y,NaN,1,8
8,Mondii,completed,y,1,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,y,NaN,NaN,9
9,Mondii,COMPLETED,Y,1,5.0,5.0,5.0,5.0,4.0,3.0,4.0,4.0,4.0,4.0,Y,NaN,NaN,10
10,Mondii,Completed,Y,1,5.0,4.0,3.0,5.0,4.0,3.0,4.0,4.0,4.0,4.0,Y,NaN,NaN,11
11,Mondii,completed,Y,1,4.0,4.0,5.0,5.0,3.0,4.0,4.0,5.0,5.0,5.0,Y,NaN,NaN,12
12,Mondii,completed,Y,1,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Y,NaN,NaN,13
13,Mondii,completed,Y,1,NaN,3.0,3.0,NaN,3.0,4.0,4.0,3.0,4.0,4.0,Y,NaN,NaN,14
14,Mondii,did not get time to use it,y,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,Mondii,Did not receive kit and is not aware of the It...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,Mondii,"Did not use app,phone problems",Y,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,Mondii,"Did not use app,phone problems",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
18,Mondii,"Did not use app,phone problems",Yes,NaN,5.0,4.0,3.0,4.0,5.0,3.0,4.0,4.0,3.0,3.0,Yes,NaN,No Challenges,19
19,Mondii,"Did not use the app ,lost phone before testing",Y,"6 Did not us the app ,lost phone before testing",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
20,Mondii,did not use the kit & the app,yes,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
21,Mondii,did not use the kit & the app,yes,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
22,Mondii,did not use the kit & the app,yes,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
23,Mondii,did not use the kit & the app,yes,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
24,Mondii,did not use the kit & the app,yes,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
25,Mondii,did not use the kit & the app,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
26,Mondii,Failed to upload results as it kept taking her...,Y,6 refer to comments section,5.0,5.0,5.0,4.0,0.0,3.0,4.0,4.0,4.0,5.0,Y,NaN,5 Uploading results,27
27,Mondii,Failed to upload the results,Y,6 refer to comments section,5.0,5.0,5.0,5.0,0.0,3.0,5.0,5.0,5.0,5.0,Y,NaN,5 Uploading results,28
28,Mondii,"First Attempt Voice mail 1,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29
29,Mondii,forgot to use the app,y,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,785
785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,786
786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,787
787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788
788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,789
789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,790
790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,791
791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,792
792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,793
793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,794
794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,795
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,796
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,797
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,798
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,799
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800
800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,801
801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,802
802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,803
803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,804
804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,805
805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,806
806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,807
807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,808
808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,809
809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,810
810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811
811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,812
812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813
813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,814